// Markdown → HTML for the docs, at build time only (never shipped to the browser).
// - Code blocks are highlighted by Shiki with both themes as CSS variables; the stylesheet
//   picks one with light-dark(), so code follows the colour scheme without JavaScript. The
//   variables are set by classes (`sl-cf222e sd-ff7b72`), not `style` attributes, so pages have
//   no inline styles and the CSP needs no 'unsafe-inline' (docs/design-docs/0003-hosting.md).
// - Headings get stable ids and a self-link, and h2/h3 are collected for the page outline.
import { Marked, type Tokens } from 'marked';
import { createHighlighter, type Highlighter, type ShikiTransformer } from 'shiki';

export interface Heading {
  readonly depth: 2 | 3;
  readonly id: string;
  readonly text: string;
}

export interface Rendered {
  readonly html: string;
  readonly headings: readonly Heading[];
}

const LANGS = ['ts', 'tsx', 'js', 'html', 'css', 'sh', 'json', 'vue'] as const;
const THEMES = { light: 'github-light-default', dark: 'github-dark-default' } as const;

let highlighter: Promise<Highlighter> | undefined;
const getHighlighter = (): Promise<Highlighter> =>
  (highlighter ??= createHighlighter({ themes: Object.values(THEMES), langs: [...LANGS] }));

/** Shiki's CSS variables and the class prefix that sets each one. */
const VARIABLES = {
  '--shiki-light': 'sl',
  '--shiki-dark': 'sd',
  '--shiki-light-bg': 'slb',
  '--shiki-dark-bg': 'sdb',
} as const;
type Variable = keyof typeof VARIABLES;
const isVariable = (name: string): name is Variable => Object.hasOwn(VARIABLES, name);

/** `--shiki-light:#CF222E;--shiki-dark:#FF7B72` → `sl-cf222e sd-ff7b72`. */
export function styleClasses(style: string): string[] {
  return style
    .split(';')
    .filter((declaration) => declaration.trim() !== '')
    .map((declaration) => {
      const [name = '', value = ''] = declaration.split(':').map((part) => part.trim());
      if (!isVariable(name) || !/^#[0-9a-f]{6}$/i.test(value))
        throw new Error(`Shiki: no class for the style "${declaration}" (src/content/markdown.ts)`);
      return `${VARIABLES[name]}-${value.slice(1).toLowerCase()}`;
    });
}

/** Moves Shiki's `style` attributes into classes (see the top of this file). */
const styleToClass: ShikiTransformer = {
  name: 'gyral-dev:style-to-class',
  pre(node) {
    const style = node.properties['style'];
    if (typeof style !== 'string') return;
    for (const name of styleClasses(style)) this.addClassToHast(node, name);
    delete node.properties['style'];
  },
  span(node) {
    const style = node.properties['style'];
    if (typeof style !== 'string') return;
    for (const name of styleClasses(style)) this.addClassToHast(node, name);
    delete node.properties['style'];
  },
};

/**
 * The stylesheet for those classes: one rule per colour of each theme, so every class Shiki can
 * produce is defined. Written to src/styles/code.css by `pnpm sync:code-css`; a test fails
 * when the file is out of date (a Shiki or theme upgrade).
 */
export async function codeCss(): Promise<string> {
  const shiki = await getHighlighter();
  const rules: string[] = [];
  for (const [scheme, name] of Object.entries(THEMES)) {
    const theme = shiki.getTheme(name);
    const colours = new Set([
      theme.fg,
      ...theme.settings.flatMap((s) => s.settings.foreground ?? []),
    ]);
    const [fg, bg] = scheme === 'light' ? (['sl', 'slb'] as const) : (['sd', 'sdb'] as const);
    const variable = scheme === 'light' ? '--shiki-light' : '--shiki-dark';
    for (const colour of [...colours].map((c) => c.toLowerCase()).sort()) {
      rules.push(`  .${fg}-${colour.slice(1)} {\n    ${variable}: ${colour};\n  }`);
    }
    const background = theme.bg.toLowerCase();
    rules.push(`  .${bg}-${background.slice(1)} {\n    ${variable}-bg: ${background};\n  }`);
  }
  return `/* Generated by \`pnpm sync:code-css\` from Shiki's ${Object.values(THEMES).join(' and ')} themes
   (src/content/markdown.ts, codeCss). Do not edit: code blocks set these classes instead of
   inline styles, so the CSP's style-src needs no 'unsafe-inline'. */
@layer components {
${rules.join('\n\n')}
}
`;
}

const escapeHtml = (text: string): string =>
  text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

const ENTITIES: Readonly<Record<string, string>> = {
  amp: '&',
  lt: '<',
  gt: '>',
  quot: '"',
  apos: "'",
  nbsp: '\u00a0',
};

/** One character reference (`&amp;`, `&#39;`, `&#x27;`) decoded; an unknown name is kept. */
const decodeEntity = (whole: string, ref: string): string => {
  if (!ref.startsWith('#')) return ENTITIES[ref] ?? whole;
  const code =
    ref[1] === 'x' || ref[1] === 'X' ? parseInt(ref.slice(2), 16) : parseInt(ref.slice(1), 10);
  return Number.isInteger(code) && code > 0 && code <= 0x10ffff
    ? String.fromCodePoint(code)
    : whole;
};

/** Plain text from rendered inline HTML: tags dropped, entities decoded (the outline escapes it again). */
const toText = (html: string): string =>
  html.replace(/<[^>]+>/g, '').replace(/&(#x[0-9a-f]+|#[0-9]+|[a-z]+);/gi, decodeEntity);

/**
 * `Getting started!` → `getting-started`. Takes text or rendered inline HTML: tags are dropped
 * and entities decoded before punctuation is, so `What&#39;s inside` (Marked's escaped
 * apostrophe) is `whats-inside`, not `what39s-inside`.
 */
export const slugify = (text: string): string =>
  toText(text)
    .toLowerCase()
    .replace(/[^\p{L}\p{N}\s-]/gu, '')
    .trim()
    .replace(/\s+/g, '-');

const isLang = (lang: string): lang is (typeof LANGS)[number] =>
  (LANGS as readonly string[]).includes(lang);

/** One highlighted code block, as the docs render it (a `<figure class="code">`). */
export async function highlight(code: string, lang: (typeof LANGS)[number]): Promise<string> {
  const shiki = await getHighlighter();
  const html = shiki.codeToHtml(code.trim(), {
    lang,
    themes: THEMES,
    defaultColor: false,
    transformers: [styleToClass],
  });
  return `<figure class="code" data-lang="${lang}">${html}</figure>`;
}

export async function renderMarkdown(source: string): Promise<Rendered> {
  const shiki = await getHighlighter();
  const headings: Heading[] = [];
  const used = new Map<string, number>();

  const marked = new Marked({
    gfm: true,
    renderer: {
      heading(this: { parser: { parseInline: (t: Tokens.Generic[]) => string } }, token) {
        const inner = this.parser.parseInline(token.tokens);
        if (token.depth === 1) return `<h1>${inner}</h1>\n`;
        const base = slugify(inner) || 'section';
        const seen = used.get(base) ?? 0;
        used.set(base, seen + 1);
        const id = seen === 0 ? base : `${base}-${String(seen)}`;
        if (token.depth === 2 || token.depth === 3) {
          headings.push({ depth: token.depth, id, text: toText(inner) });
        }
        return `<h${String(token.depth)} id="${id}"><a class="anchor" href="#${id}">${inner}</a></h${String(token.depth)}>\n`;
      },
      code(token) {
        const lang = (token.lang ?? '').split(/\s/)[0] ?? '';
        const label = lang === '' ? 'text' : lang;
        const highlighted = isLang(lang)
          ? shiki.codeToHtml(token.text, {
              lang,
              themes: THEMES,
              defaultColor: false,
              transformers: [styleToClass],
            })
          : `<pre class="shiki" tabindex="0"><code>${escapeHtml(token.text)}</code></pre>`;
        return `<figure class="code" data-lang="${escapeHtml(label)}">${highlighted}</figure>\n`;
      },
      link(this: { parser: { parseInline: (t: Tokens.Generic[]) => string } }, token) {
        const inner = this.parser.parseInline(token.tokens);
        const external = /^https?:\/\//.test(token.href);
        const title = token.title ? ` title="${escapeHtml(token.title)}"` : '';
        const rel = external ? ' rel="external"' : '';
        return `<a href="${escapeHtml(token.href)}"${title}${rel}>${inner}</a>`;
      },
    },
  });

  const html = await marked.parse(source);
  return { html, headings };
}
